### ISSUE TITLE
Error: THREE.Spherical is not a constructor

### ISSUE THREAD

**Issue by yellowblood** [avish/ripplez#1]
![image](https://cloud.githubusercontent.com/assets/1921800/24368037/a0152cfa-1327-11e7-9129-c8999c578a41.png)

**Comment by yellowblood** [comment]
@avish what gives man, what gives

**Comment by avish** [comment]
Lesson: don't use "latest" URLs when referencing third-party scripts for a project you don't intend to actively maintain. Also don't assume any JavaScript library will keep a stable API for longer than a few months.

**Comment by yellowblood** [comment]
@avish you may now approve my PR, this is super important.
